matchmaker-configuration:
  # example dungeon in rpgcore configs
  tanjeen:
    # How many players to play content (will bypass local server config)
    players: 2
    # Use server with the least players online
    servers:
      - "shard-01"
      - "shard-02"
    # Player limit of the servers
    maximum-players: 50
