package me.blutkrone.rpgcore.hud.editor.bundle.mechanic;

import me.blutkrone.rpgcore.hud.editor.annotation.EditorTooltip;
import me.blutkrone.rpgcore.hud.editor.annotation.value.EditorBoolean;
import me.blutkrone.rpgcore.hud.editor.annotation.value.EditorBundle;
import me.blutkrone.rpgcore.hud.editor.bundle.modifier.EditorModifierNumber;
import me.blutkrone.rpgcore.skill.mechanic.AbstractCoreMechanic;
import me.blutkrone.rpgcore.skill.mechanic.TauntMechanic;
import me.blutkrone.rpgcore.util.ItemBuilder;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

public class EditorTauntMechanic extends AbstractEditorMechanic {

    @EditorBundle(name = "Factor")
    @EditorTooltip(tooltip = "How much rage to generate")
    public EditorModifierNumber factor = new EditorModifierNumber();
    @EditorBundle(name = "Limit")
    @EditorTooltip(tooltip = "Upper limit of rage generated")
    public EditorModifierNumber limit = new EditorModifierNumber();
    @EditorBoolean(name = "Quickswap")
    @EditorTooltip(tooltip = "Ignore mob cooldown on swapping targets")
    public boolean quickswap = false;

    @Override
    public AbstractCoreMechanic build() {
        return new TauntMechanic(this);
    }

    @Override
    public ItemStack getPreview() {
        return ItemBuilder.of(Material.LAVA_BUCKET)
                .name("§fTaunt Mechanic")
                .build();
    }

    @Override
    public String getName() {
        return "Taunt Mechanic";
    }

    @Override
    public List<String> getInstruction() {
        List<String> instruction = new ArrayList<>();
        instruction.add("Taunt Mechanic");
        instruction.add("Mobs only track rage of one target, if a non-target");
        instruction.add("Generates rage, it'll reduce rage and eventually swap");
        instruction.add("Targets to someone else.");
        instruction.add("");
        instruction.add("Auto attacks and detection have a maximum of 1 rage, damage");
        instruction.add("Does not inherently generate rage.");
        instruction.add("");
        instruction.add("Focus of the rage holder reduces rage generated by other");
        instruction.add("Subjects.");
        return instruction;
    }
}
