package me.blutkrone.rpgcore.entity.entities;

import me.blutkrone.rpgcore.api.entity.EntityProvider;
import org.bukkit.entity.LivingEntity;

/**
 * Rage is tracked only for the current target.
 * <p>
 * Rage goes for up to 10 points.
 * <p>
 * Hitting without a target generates 5 points of rage.
 * <p>
 * Highest DPS gains 1 point of rage every second.
 * <p>
 * If rage is reduced to 0 re-focus with 5 points of rage.
 * <p>
 * Aggro holder can reduce aggro generated by others.
 * <p>
 * Display rage with white-to-red tint of focus name.
 */
public class CoreMob extends CoreEntity {

    public CoreMob(LivingEntity entity, EntityProvider provider) {
        super(entity, provider);
    }
}
